name: "workspace"

services:
    grafana:
        image: grafana/grafana-enterprise:12.0.4-ubuntu
        restart: unless-stopped
        ports:
            - '3333:3000'
        volumes:
          - grafana-storage:/var/lib/grafana
    
    clickhouse:
        image: clickhouse/clickhouse-server:25.3.2
        hostname: workspace-clickhouse
        ports:
            - "8123:8123"
            - "9000:9000"
        mem_limit: "1.5g"
        cpus: "1"
        ulimits:
            nproc: 262144
            nofile:
                soft: 262144
                hard: 262144
        restart: unless-stopped
        volumes:
            - clickhouse_data:/var/lib/clickhouse:delegated # macOS: reduce FS sync churn
            - clickhouse_logs:/var/log/clickhouse-server
            - ./config/clickhouse/config.d:/etc/clickhouse-server/config.d:ro,delegated
            - ./config/clickhouse/users.d:/etc/clickhouse-server/users.d:ro,delegated
            - ./config/clickhouse/initdb.d:/docker-entrypoint-initdb.d:ro
        environment:
            CLICKHOUSE_SKIP_USER_SETUP: "1"
            CLICKHOUSE_DEFAULT_ACCESS_MANAGEMENT: "1"
        healthcheck:
            test: ["CMD-SHELL", "curl -sf http://localhost:8123/ping >/dev/null"]
            interval: 30s
            timeout: 10s
            retries: 5

    rabbitmq:
        image: rabbitmq:4-alpine
        hostname: workspace-rabbitmq
        ports:
            - "5672:5672"
        environment:
            RABBITMQ_DEFAULT_VHOST: zero
            RABBITMQ_DEFAULT_USER: rabbit
            RABBITMQ_DEFAULT_PASS: carrot
            RABBITMQ_ERLANG_COOKIE: '+ZDmmt92+hkVxcnwjDf+50alwjxOceLSm0ZXNe8f'
        volumes:
            - rabbitmq_data:/var/lib/rabbitmq
        healthcheck:
            test: rabbitmq-diagnostics check_port_connectivity
            interval: 30s
            timeout: 10s
            retries: 5
            start_period: 10s
        restart: unless-stopped

    postgres:
        image: postgres:17.3-alpine3.21
        shm_size: 128mb
        ports:
            - "5432:5432"
        volumes:
            - postgres_data:/var/lib/postgresql/data
        user: postgres
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: emmastone
            POSTGRES_DB: postgres
            POSTGRES_INITDB_ARGS: "--locale-provider=icu --icu-locale=tr-TR"
            LANG: tr_TR.utf8
        healthcheck:
            test: [ "CMD-SHELL", "pg_isready" ]
            interval: 30s
            timeout: 20s
            retries: 5
        restart: unless-stopped

    redis:
        image: redis:7.4.2-alpine3.21
        ports:
            - "6379:6379"
        volumes:
            - redis_data:/data
        environment:
            REDIS_PASSWORD: jenniferlawrence
        command: redis-server --requirepass jenniferlawrence --save 60 1 --loglevel warning
        healthcheck:
            test: ['CMD', 'redis-cli', 'ping']
            interval: 30s
            timeout: 20s
            retries: 5
        restart: unless-stopped

networks:
    default:
        name: workspace
        external: true

volumes:
    rabbitmq_data:
    postgres_data:
    redis_data:
    clickhouse_data:
    clickhouse_logs:
    grafana-storage:
